project/urls.py
# São as importações realizadas de forma a utilizar parte do django.
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

# Lista responsável por organizar as urls do sistema.
urlpatterns = [
    path('', include('sistema.urls')),
    path('admin/', admin.site.urls),
]

# path() -> é um método do django que permite a inserção de uma url.

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/urls.py
# São as importações realizadas de forma a utilizar partes do django
from django.urls import path
# Importação do diretório views.py, onde tem a view index e a view listarPacientes.
from sistema import views

app_name = 'sistema'


urlpatterns = [
    path('', views.index, name='index'),
    path('pacientes/', views.listarPacientes, name= 'pacientes'),
    path('pacientes/novo/', views.criarPaciente, name= 'criarPaciente'),
    path('pacientes/perfil/<int:paciente_id>', views.perfilPaciente, name= 'perfil_paciente'),
    path('medicos/', views.listarMedicos, name= 'medicos'),
    path('medicos/novo/', views.criarMedico, name= 'criarMedico'),
    path('login/', views.login, name='login'),
]

sistema/models.py
# Importação do módulo models que tras métodos do banco de dados.
from django.db import models

#Impotação do módulo TIMEZONE que traz datas e horários.
from django.utils import timezone

# Aqui fica o model do paciente

class Paciente(models.Model):
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    criacao_data = models.DateTimeField(default=timezone.now)
    mensagem = models.TextField(blank=True)
    ativo = models.BooleanField(default=True)
    imagem = models.ImageField(upload_to='img/%Y/%m/', blank=True)
    
    def __str__(self):
        return f'{self.nome} {self.sobrenome}'

# Aqui fica o model da especialidade    
class Especialidade(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nome}'
    

class Medico(models.Model):
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    crm = models.CharField(max_length=6)
    email = models.EmailField()
    telefone = models.CharField(max_length=50)
    criacao_data = models.DateTimeField(default=timezone.now)
    mensagem = models.TextField(blank=True)
    ativo = models.BooleanField(default=True)
    imagem = models.ImageField(upload_to='img/%Y/%m', blank=True)
    especialidade = models.ForeignKey(Especialidade, default=1, on_delete=models.CASCADE, verbose_name='Especialidade')

    def __str__(self):
        return f'{self.nome} {self.sobrenome}'

class Consulta(models.Model):
    paciente_id = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    medico_id = models.ForeignKey(Medico, on_delete=models.CASCADE, null=True)
    horario = models.DateTimeField()
    descricao = models.TextField(blank=True)
    confirmar =  models.BooleanField(default=True)
    status = models.CharField(default = 'A',
                    max_length = 1,
                    choices = (
                        ('A', 'AGENDADA'),
                        ('C', 'CANCELADA'),
                        ('M', 'CONFIRMADA'),                              
                        ('R', 'REALIZADA'),
                    )
                    )
# A -> AGENDADA
# C -> CANCELADA
# M -> CONFIRMADA
# R -> REALIZADA    
    def __str__(self):
        return f'Consulta {self.status} com sucesso.'

sistema/forms.py
from django import forms # Importa o módulo de forms do django
from .models import Paciente
from .models import Medico

# Criando o form baseado no model Paciente(ModelForm)
class PacienteForm(forms.ModelForm):
    class Meta: # a classe meta serve para configurar o form
        model = Paciente # Define qual o model que i form representa
        fields = ['nome', 'sobrenome', 'email', 'telefone','mensagem',]
        # São os campos que serão exibidos no form(HTML)

class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields = ['nome', 'sobrenome', 'email', 'telefone', 'crm', 'especialidade',]





sistema/views.py
from django.shortcuts import render

# Aqui fica a primeira view
def index(request):
    return render(
        request,
        'global/base.html'
    )

def marcos(request):
    return render(
        request,
        'global/marcos.html'
    )

# REQUEST - RESPONSE - RENDER

sistema/views/medico_views.py
from django.shortcuts import get_object_or_404, render, redirect
from sistema.forms import MedicoForm
from sistema.models import Medico

def listarMedicos(request):
    medicos = Medico.objects.all()

    context = { 
        'medicos': medicos,
    }

    return render(
        request,
        'medico/listar.html',
        context,
    )



def criarMedico(request):
    if request.method == 'POST':
        form = MedicoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect( '/medicos')
    else:
        form = MedicoForm()

    return render(
        request,
        'medico/criar.html',
        {'form': form}    
    )

sistema/views/paciente_views.py
from django.shortcuts import get_object_or_404, render, redirect
from sistema.forms import PacienteForm
from sistema.models import Paciente

# View referente a listagem dos Pacientes
def listarPacientes(request):
    pacientes = Paciente.objects.all() # Váriavel paciente está guardando todos os objetos da tabela Paciente.

    context = { # Declaração de um dicionário que possui a chave pacientes e o valor pacientes(variável criada acima).
        'pacientes': pacientes,
    }

    return render(
        request,
        'paciente/listar.html',
        context,
    )


# View referente a criação dos Pacientes
def criarPaciente(request):
    # Verificar se a requisição é do tipo POST
    if request.method == 'POST':
        # Cria uma instância do form e preenche com os dados enviados.
        form = PacienteForm(request.POST, request.FILES)
        # POST -> Contém os campos do form (nome, email, etc...)
        # FILES -> Contém o arquivo enviados (imagens)
        if form.is_valid():
            # Se os dados forem válidos, é salvo um novo paciente no BD.
            form.save()
            return redirect( '/pacientes')
    else:
        # Se uma requisição for do tipo GET, exibe um formulário vazio
        form = PacienteForm()

    return render(
        request,
        'paciente/cadastro.html',
        {'form': form}    
    )

#View referente ao paciente_unico(perfil) do Paciente
def perfilPaciente(request, paciente_id):
    paciente_unico = get_object_or_404( # Método utilizado para mostrar o Paciente ou retornar erro 404
        Paciente, pk=paciente_id # Paciente é o model, pk=paciente_id está definindo através de qual campo(coluna) o objeto será retornado.
    )
    titulo = f'{paciente_unico.nome} {paciente_unico.sobrenome}' # Cria um  título com o nome e sobrenome do Paciente atual.
    context = {
        'paciente_unico': paciente_unico,
        'titulo': titulo,
    }

    return render(
        request,
        'paciente/perfil.html',
        context,
    )

sistema/views/site_views.py
from django.shortcuts import render

# Aqui fica a primeira view
def index(request):
    return render(
        request,
        'global/base.html'
    )

def login(request):
    return render(
        request,
        'usuario/login.html'
    )

# REQUEST - RESPONSE - RENDER

sistema/templates/index.html
{% extends "global/base.html" %}

sistema/templates/medico/cadastro.html
<h1>Cadastrar Medico</h1>

<!-- Formulário que envia os dados via POST e aceita enviar arquivos-->

<form method='POST'>
    {% csrf_token %} <!-- Proteção contra ataques do tipo CSRF (Obrigatório)-->

    <!-- Exibição dos campos para enviar o fomulário -->

    {{ form.as_p }}
    <!-- Exibir as informções do forms como parágrafos -->

    <button type='submit'>Salvar</button>
</form>

sistema/templates/medico/criar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% include "global/partials/_head.html" %}
  </head>
  <body>
    <header class="header">
      <div class="container header-container">
        <a href="#" class="logo"><img src={% static "/global/assets/logo.svg" %} alt="Logo da
          consulta.me"></a>
        <div class="navbar-form">
          <a href="#" class="btn-link">Login</a>
        </div>
      </div>
    </header>

    <h1>Cadastrar Médico</h1>

    <!-- Formulário que envia os dados via POST e aceita enviar arquivos-->

    <form method="POST">
      {% csrf_token %}
      <!-- Proteção contra ataques do tipo CSRF (Obrigatório)-->

      <!-- Exibição dos campos para enviar o fomulário -->

      {{ form.as_p }}
      <!-- Exibir as informções do forms como parágrafos -->

      <button type="submit">Salvar</button>
    </form>

    <footer>{% include "global/partials/_footer.html" %}</footer>
  </body>
</html>

sistema/templates/medico/listar.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% include "global/partials/_head.html" %}
  </head>
  <body>
    <header>
        {% include "global/partials/_header.html" %}
    </header>

    {%block conteudo%}
    <div class="responsive-table">
      <table class="medico-table">
        <caption class="table-caption">
          Listagem de Médicos
        </caption>

        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">NOME</th>
            <th class="table-header">SOBRENOME</th>
            <th class="table-header">EMAIL</th>
            <th class="table-header">CRM</th>
            <th class="table-header">TELEFONE</th>
          </tr>
        </thead>

        <tbody>
          {% for medico in medicos %}
          <tr class="table-row">
            <td class="table-cel">{{ medico.id }}</td>
            <td class="table-cel">{{ medico.nome }}</td>
            <td class="table-cel">{{ medico.sobrenome }}</td>
            <td class="table-cel">{{ medico.email }}</td>
            <td class="table-cel">{{medico.crm}}</td>
            <td class="table-cel">{{ medico.telefone }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    {% endblock conteudo %}

    <footer>{% include "global/partials/_footer.html" %}</footer>
  </body>
</html>

sistema/templates/paciente/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% include "global/partials/_head.html" %}
  </head>
  <body>
    <header class="header">
      <div class="container header-container">
        <a href="#" class="logo"
          ><img src={% static "/global/assets/logo.svg" %} alt="Logo da
          consulta.me"></a
        >
        <div class="navbar-form">
          <a href="#" class="btn-link">Login</a>
        </div>
      </div>
    </header>
    <h1>Cadastrar Paciente</h1>

    <!-- Formulário que envia os dados via POST e aceita enviar arquivos-->

    <form method="POST">
      {% csrf_token %}
      <!-- Proteção contra ataques do tipo CSRF (Obrigatório)-->

      <!-- Exibição dos campos para enviar o fomulário -->

      {{ form.as_p }}
      <!-- Exibir as informções do forms como parágrafos -->

      <button type="submit">Salvar</button>
    </form>

    <footer>{% include "global/partials/_footer.html" %}</footer>
  </body>
</html>

sistema/templates/paciente/listar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% include "global/partials/_head.html" %}
  </head>
  <body>
    <header class="header">
      <div class="container header-container">
        <a href="#" class="logo"
          ><img src={% static "/global/assets/logo.svg" %} alt="Logo da
          consulta.me"></a
        >
        <div class="navbar-form">
          <a href="#" class="btn-link">Login</a>
        </div>
      </div>
    </header>
    
    {%block conteudo%} 
    <div class="responsive-table">
      <table class="pacientes-table">
        <caption class="table-caption">
          Listagem de pacientes
        </caption>

        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">NOME</th>
            <th class="table-header">SOBRENOME</th>
            <th class="table-header">EMAIL</th>
            <th class="table-header">TELEFONE</th>
            <th class="table-header">IMAGEM</th>
          </tr>
        </thead>

        <tbody>
          {% for paciente in pacientes %}
          <tr class="table-row">
            <td class="table-cel">
              <a
                class="table-link"
                href="{% url 'sistema:perfil_paciente' paciente.id %}"
              >
                {{ paciente.id }}</a
              >
            </td>
            <td class="table-cel">{{ paciente.nome }}</td>
            <td class="table-cel">{{ paciente.sobrenome }}</td>
            <td class="table-cel">{{ paciente.email }}</td>
            <td class="table-cel">{{ paciente.telefone }}</td>
            <td class="table-cel">
              {% if paciente.imagem %}
              <img
                src="{{paciente.imagem.url}}"
                alt="Imagem do paciente"
                style="max-height: 80px"
              />
              {% else %} sem imagem {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>



{% endblock conteudo %} 
    <footer>{% include "global/partials/_footer.html" %}</footer>
  </body>
</html>

{% comment %} {% block conteudo %} {% for paciente in
pacientes %} {{ paciente.nome}} {{paciente.id}} Utilizando interpolação
(Acessando um objeto e um atributo) {% endfor %} {% endblock conteudo %} 
{%endcomment %}

sistema/templates/paciente/perfil.html

{% include "global/partials/_head.html" %}
{% include "global/partials/_header.html" %}
{% block conteudo %}
<div class="single-pacient">
    <h1 class="single-pacient__name">
        {{titulo}}
    </h1>






{% endblock conteudo %}
{% include "global/partials/_footer.html" %}

sistema/templates/usuario/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% include "global/partials/_head.html" %}
  </head>
  <body>
    <header>
      {% include "global/partials/_header.html" %}
      <style>
        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 20px;
        }

        .card {
          background-color: #fff;
          border-radius: 8px;
          padding: 40px;
          box-shadow: 0px 7px 50px rgba(12, 5, 83, 0.09);
          margin: 20px 0;
        }

        .form-card {
          min-width: 800px;
          width: 100%;
        }

        .form-group {
          margin-bottom: 20px;
        }

        .form-group label {
          color: #333;
          font-weight: bold;
          display: block;
          margin-bottom: 8px;
        }

        .form-group input,
        .form-group select {
          width: 100%;
          padding: 12px;
          border-radius: 8px;
          border: 1px solid #81b7e1;
          background-color: #f3f9fa;
          color: #6b6e71;
        }

        .btn {
          padding: 12px 20px;
          border-radius: 8px;
          font-weight: bold;
          cursor: pointer;
          border: none;
          transition: all 0.3s ease;
        }

        .btn-primary {
          background-color: #339cff;
          color: #fff;
        }

        .title {
          color: #0b3b60;
          font-size: 28px;
          font-weight: bold;
          margin-bottom: 30px;
        }

        .footer {
    background-color: #0b3b60;
    color: #e7ebef;
    padding: 20px 0;
    text-align: center;
    margin-top: auto;
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 60px;  
  }
      </style>
    </header>

    <main class="container">
      <section class="card form-card">
        <h2 class="title">Login</h2>

        <form action="#" method="post">
          <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="username" required />
          </div>

          <div class="form-group">
            <label for="senha">Senha:</label>
            <input type="password" id="senha" name="password" required />
          </div>

          <button class="btn btn-primary" title="Entrar">Entrar</button>
        </form>
      </section>
    </main>

    <footer>{% include "global/partials/_footer.html" %}</footer>
  </body>
</html>